vim.keymap.set("n", "<leader>gs", vim.cmd.Git)
vim.keymap.set("n", "<leader>gd", vim.cmd.Gdiff)
vim.keymap.set("n", "<leader>gds", vim.cmd.Gdiffsplit)
vim.keymap.set("n", "<leader>gc", vim.cmd.Gcommit)
vim.keymap.set("n", "<leader>gl", vim.cmd.Glog)
