vim.keymap.set("n", "<leader>gs", vim.cmd.Git, { desc = "[G]it [S]tatus" })
vim.keymap.set("n", "<leader>gd", vim.cmd.Gdiff, { desc = "[G]it [D]iff" })
vim.keymap.set("n", "<leader>gds", vim.cmd.Gdiffsplit, { desc = "[G]it [D]iff] [S]plit" })
vim.keymap.set("n", "<leader>gc", vim.cmd.Gcommit, { desc = "[G]it [C]ommit" })
vim.keymap.set("n", "<leader>gl", vim.cmd.Glog, { desc = "[G]it [L]og" })
