require('telescope').setup({ file_ignore_patterns = { "node%_modules/.*" } })

local builtin = require('telescope.builtin')
vim.keymap.set('n', '<Space><Space>', builtin.oldfiles, {})
vim.keymap.set("n", "<leader>sd", builtin.diagnostics, { desc = "[S]earch [D]iagnostics" })
vim.keymap.set("n", "<leader>jl", builtin.jumplist, { desc = "[J]ump [L]ist" })
vim.keymap.set("n", "<leader>km", builtin.keymaps, { desc = "[K]ey[M]aps" })
vim.keymap.set("n", "<leader>rg", builtin.registers, { desc = "[R]egisters" })
vim.keymap.set("n", "<leader>ht", builtin.help_tags, { desc = "[H]elp [T]ags" })
vim.keymap.set("n", "<leader>sw", builtin.grep_string, { desc = "[S]earch current [W]ord" })
vim.keymap.set('n', '<C-p>', builtin.find_files, {desc = "Find [F]iles"})
vim.keymap.set('n', '<leader>pf', builtin.git_files, {desc = "Find [G]it [F]iles"})
vim.keymap.set('n', '<leader>f', builtin.live_grep, {desc = "Search [A]ll"})
vim.keymap.set('n', '<leader>ps', function()
	builtin.grep_string({ search = vim.fn.input("Grep > ") });
end, {desc = "Search [S]tring"})
